name: Build mkdocs
description: Parametrized mkdocs building

inputs:
  github_token:
    description: github token
    required: true

  site_url:
    description: Set `MKDOCS_SITE_URL` env var
    default: ""
    required: true

  working_dir:
    description: Parent directory that contains mkdocs.yml
    default: ${{ github.workspace }}/docs

  output_dir:
    description: Where we will output the resulting webpage
    default: ${{ github.workspace }}/book

  upload_github_page:
    description: Upload github-page
    default: "false"

  repo_url:
    description: URL of the repo
    default: ${{ github.server_url }}/${{ github.repository }}

outputs:
  artifact_id:
    description: "Artifact id uploaded (is an empty string in case of `upload_github_page: false`)"
    value: ${{ steps.upload-artifact.outputs.artifact_id }}

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Configure uv
      working-directory: ${{ inputs.working_dir }}
      shell: bash
      run: uv python install

    - name: uv install deps
      id: uv-setup
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: uv sync --all-extras --dev
      continue-on-error: true

    # Fallback for whenever 'watchdog' dep gives issues
    # FIXME: Remove me whenever 'watchdog' doesnt give issues anymore
    - name: uv install deps
      shell: bash
      if: ${{ steps.uv-setup.outcome == 'failure' }}
      working-directory: ${{ inputs.working_dir }}
      run: uv sync --all-extras --dev --no-binary-package=watchdog

    - name: Build book
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      env:
        MKDOCS_SITE_URL: ${{ inputs.site_url }}
        MKDOCS_REPO_URL: ${{ inputs.repo_url }}
        _OUTPUT_DIR: ${{ inputs.output_dir }}
      run: |
        source .venv/bin/activate
        set -euo pipefail
        mkdocs build -d $_OUTPUT_DIR

    - name: Restore lychee cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .lycheecache
        key: cache-lychee-${{ github.sha }}
        restore-keys: cache-lychee-

    - name: Check links
      uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2.7.0
      with:
        args: --root-dir ${{ inputs.output_dir }} ${{ inputs.output_dir }}
        jobSummary: true
        fail: false
        token: ${{ inputs.github_token }}

    - name: Setup Pages
      if: ${{ inputs.upload_github_page == 'true' }}
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      with:
        token: ${{ inputs.github_token }}

    - name: Upload artifact
      if: ${{ inputs.upload_github_page == 'true' }}
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
      id: upload-artifact
      with:
        path: ${{ inputs.output_dir }}
        token: ${{ inputs.github_token }}
        retention-days: 3

    - name: Deploy to GitHub Pages
      if: ${{ inputs.upload_github_page == 'true' }}
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
      with:
        token: ${{ inputs.github_token }}
